In [317]:
# import numpy
import numpy as np

In [318]:
# read the .txt document to a variable
task_2_txt = open("task_II_data.txt","r")

# read the text lines from the file to a variable
t2_lines = task_2_txt.readlines()

In [319]:
# intialize empty array
# this is named test, because it started as a test array, but eventually became the one I used
test = []

In [320]:
# split original data at "," and add to the end of the empty array
for i in range( 0 , len(t2_lines) ):
    test.append(t2_lines[i].split(","))

In [321]:
# remove "/n" from the last element of each line
for i in range( 0 , len(test) ):
    test[i][len(test[i])-1] = test[i][len(test[i])-1][0:len(test[i][len(test[i])-1])-1]

In [322]:
# convert the elements to floats
for i in range( 0 , len(test) ):
    for j in range( 0 , len(test[i]) ):
        test[i][j] = float(test[i][j])

In [323]:
# convert the array to a numpy array
test = np.array(test)

In [324]:
# go through each line and element and delete that line if any of its elements is nan
x = len(test)
i = 0

while( i < x ):
    for j in range( 0 , len(test[i]) ):
        if(np.isnan(test[i][j])):
            test = np.delete( test , (i) , 0) # if np.isnan(test[i][j])==True, delete row
            x = len(test) # update upper bound of while loop when one line is deleted
            i = i - 1 # to check the new ith row again after deleting
            break # break the inner for-loop when nan is found
    i = i + 1

In [325]:
for i in range ( 0 , 4 ):
    print("Column "+str(i)+": ")
    print("   Mean: "+str(np.mean(test , axis = 0)[i]))
    print("   Standard deviation: "+str(np.std(test , axis = 0)[i])+"\n")

Column 0: 
   Mean: 4.999967107011116e-12
   Standard deviation: 0.9999999999931781

Column 1: 
   Mean: 1.0000084094130557e-11
   Standard deviation: 0.9999999999988219

Column 2: 
   Mean: 1.0000003949905966e-11
   Standard deviation: 1.0000000000058604

Column 3: 
   Mean: 1.0000017480749079e-11
   Standard deviation: 1.0000000000033717



In [326]:
print("Mean value of row 2: "+str(np.mean(test , axis=1)[1]))

Mean value of row 2: 0.27402897962500006


In [327]:
print("Row 3 before edit:")
print(test[2,:])
test[2] = [3,3,3,3]
print("\nRow 3 after edit:")
print(test[2,:])

Row 3 before edit:
[-0.20682088  1.34891973  1.87906991  1.28061368]

Row 3 after edit:
[3. 3. 3. 3.]


In [328]:
# prints tha rownumbers of those rows where the 2nd element is over 0.5
print("The 2nd element of the following rows are larger than 0.5: ")
testarray = np.array(np.where(test>0.5), dtype = int)

for i in range( 0 , len(np.where(test>0.5)[1])):
    if ( testarray[1][i] == 1 ):
        print("\n"+str(testarray[0][i]))
        print(test[testarray[0][i], :])

The 2nd element of the following rows are larger than 0.5: 

0
[ 1.44009018  1.31579679 -1.20351222 -0.64975055]

1
[ 1.45845961  1.12070275 -2.08544131  0.60239487]

2
[3. 3. 3. 3.]

4
[-0.05758539  1.35928316 -0.90377374  0.17181682]

5
[-1.05001347  1.42387013  0.57918597  0.59410267]

14
[-0.39320627  1.12419476  1.94996322  1.33808555]

16
[-0.79640397  0.65937073  0.36039459  1.33246741]
